import { jwtDecode } from "jwt-decode";
import { handleCreateInventory } from "../../controllers/accountant/createInventoryAc.controller";
import BaseFormModal from "../common/BaseFormModal";

const FormCreateInventoryAd = ({ onClose, onSuccess }) => {
  const herramientasPredefinidas = [
    "Alineador láser de ejes",
    "Laser tracker (rastreador láser 3D)",
    "Analizador de vibraciones",
    "Cámara termográfica",
    "Boroscopio / Videoscopio industrial",
    "Megóhmetro de 5kV / 10kV",
    "Micro-ohmímetro (Ductor)",
    "Analizador de redes y calidad de energía",
    "Multímetro True RMS industrial",
    "Pinza amperimétrica AC/DC",
    "Secuencímetro de fases",
    "Osciloscopio portátil",
    "Detector de tensión de alta seguridad",
    "Calibrador de procesos (loop calibrator)",
    "Tacómetro óptico y de contacto",
    "Estroboscopio digital",
    "Medidor de espesores por ultrasonido",
    "Equipo de ensayos no destructivos (Líquidos penetrantes)",
    "Partículas magnéticas (Yugo magnético)",
    "Durómetro portátil",
    "Rugosímetro (medidor de rugosidad superficial)",
    "Termómetro infrarrojo láser",
    "Llave dinamométrica hidráulica (cassette bajo perfil)",
    "Llave dinamométrica hidráulica (cuadradillo)",
    "Bomba hidráulica eléctrica (700 bar)",
    "Bomba hidráulica neumática",
    "Bomba hidráulica manual",
    "Mangueras hidráulicas de alta presión",
    "Llaves dinamométricas manuales (de clic)",
    "Multiplicador de par (Torque multiplier)",
    "Gatos hidráulicos de botella",
    "Cilindros hidráulicos extraplanos (Pancake)",
    "Cilindros de émbolo hueco",
    "Extractores de rodamientos hidráulicos (20-50 ton)",
    "Extractores de rodamientos mecánicos de 3 garras",
    "Calentador de inducción para rodamientos",
    "Prensa hidráulica de taller (100 ton)",
    "Torno portátil (para mecanizado in-situ)",
    "Fresadora portátil (para chaveteros y bases)",
    "Taladro de base magnética",
    "Rectificadora recta neumática (Die grinder)",
    "Rectificadora angular de 7\" y 9\"",
    "Rectificadora angular de 4.5\"",
    "Lijadora de banda portátil",
    "Equipo de soldadura TIG AC/DC",
    "Equipo de soldadura MIG/MAG",
    "Equipo de soldadura por arco manual (Inverter)",
    "Equipo de oxicorte (soplete, mangueras, manómetros)",
    "Compresor de aire industrial portátil",
    "Pistola de impacto neumática de 1\"",
    "Pistola de impacto neumática de 3/4\"",
    "Pistola de impacto neumática de 1/2\"",
    "Cincelador neumático",
    "Agujas desincrustantes neumáticas",
    "Polipasto de cadena (Tecle) de 1 ton",
    "Polipasto de cadena de 3 ton",
    "Polipasto de palanca (Señorita/Come-along)",
    "Tirfor (Cabrestante manual de cable)",
    "Grilletes de carga (tipo lira y recto)",
    "Cáncamos giratorios de elevación",
    "Eslingas de poliéster planas (varias medidas)",
    "Eslingas tubulares (reondas)",
    "Eslingas de cadena de acero grado 80/100",
    "Gato mecánico de cremallera (Railroad jack)",
    "Detector de 4 gases (espacios confinados)",
    "Trípode de rescate con malacate",
    "Ventilador/Extractor axial para espacios confinados",
    "Arnés de cuerpo completo (dielectrico/ignífugo)",
    "Eslinga de posicionamiento regulable",
    "Línea de vida retráctil",
    "Kit de bloqueo y etiquetado (LOTO)",
    "Pértigas de salvamento",
    "Puesta a tierra portátil temporal",
    "Cascos de seguridad con barbuquejo",
    "Lámparas de cabeza (Headlamps) ATEX",
    "Relojes comparadores centesimales",
    "Relojes comparadores milesimales",
    "Bases magnéticas articuladas",
    "Micrómetro de exteriores (juego 0-150mm)",
    "Micrómetro de exteriores de gran arco (300-1000mm)",
    "Micrómetro de interiores (tipo tubular)",
    "Calibrador Pie de Rey digital (500mm y 1000mm)",
    "Galgas de espesores (Feeler gauges)",
    "Galgas de radios y roscas",
    "Nivel de precisión para maquinaria (0.02mm/m)",
    "Reglas de verificación (Straight edge)",
    "Juego de llaves de golpe (fijas y de estrella)",
    "Juego de dados de impacto (socket) de 3/4\" y 1\"",
    "Juego de llaves combinadas (milimétricas y pulgadas)",
    "Llaves Allen (hexagonales) industriales mango T",
    "Llave Stillson de 24\", 36\" y 48\"",
    "Llave ajustable (Crescent) de 12\" a 24\"",
    "Alicates de presión (Vise-grip)",
    "Alicates para seguros (circlips) internos y externos",
    "Martillos de bola (varios pesos)",
    "Mazos de bronce o cobre (antichispa/antidaño)",
    "Barras de uña (Barretas)",
    "Juego de botadores y granetes",
    "ROV (Vehículo operado remotamente para inspección subacuática)",
    "Bombas de achique sumergibles industriales",
    "Llaves de golpe (de anilla y boca fija)",
    "Llaves de torque hidráulicas (cassette de bajo perfil)",
    "Bombas hidráulicas eléctricas de 700 bar",
    "Bombas hidráulicas manuales de alta presión",
    "Multiplicador de torque manual",
    "Torquímetro de click (3/4\" y 1\")",
    "Torquímetro digital",
    "Copas (dados) de impacto de cuadro 1\"",
    "Copas (dados) de impacto de cuadro 3/4\"",
    "Juego de llaves combinadas milimétricas (hasta 50mm)",
    "Juego de llaves combinadas en pulgadas (hasta 2\")",
    "Llaves Allen (hexagonales) industriales mm/pulg",
    "Llaves Torx de impacto",
    "Destornilladores de golpe",
    "Pinzas para anillos de retención (circlips) interiores/exteriores",
    "Masas de bronce (antichispa)",
    "Masas de acero (8, 10, 12 lbs)",
    "Cinceles y punzones industriales",
    "Botadores de pasadores",
    "Palancas de fuerza (Barretas)",
    "Cilindros hidráulicos de émbolo hueco",
    "Extractores de rodamientos de 3 garras (hidráulicos)",
    "Extractores de rodamientos mecánicos",
    "Prensa hidráulica de taller (50-100 ton)",
    "Taladro magnético industrial",
    "Fresas anulares para metal",
    "Esmeriladora angular de 9\"",
    "Esmeriladora angular de 4 1/2\"",
    "Rectificadora recta (Motortool) neumática",
    "Rectificadora recta eléctrica",
    "Limas rotativas de carburo de tungsteno",
    "Inversor de soldadura para electrodo revestido (SMAW)",
    "Cortadora de plasma manual",
    "Pistola de calor industrial",
    "Cepillos de copa de alambre trenzado",
    "Discos de desbaste y corte",
    "Alineador de poleas láser",
    "Bases magnéticas con ajuste fino",
    "Micrómetro de exteriores (set 0-150mm)",
    "Galgas de espesores (Feeler gauges) de precisión",
    "Reglas de planitud (rectificadas)",
    "Inclinómetro digital",
    "Cinta métrica de acero (fléxometro)",
    "Cinta pirométrica (para medir diámetros)",
    "Analizador de vibraciones portátil",
    "Tacómetro láser/contacto",
    "Estetoscopio mecánico industrial",
    "Videoscopio / Boroscopio articulado",
    "Multímetro digital True RMS",
    "Megóhmetro de aislamiento (5kV o 10kV)",
    "Detector de ausencia de tensión de alta media/tensión",
    "Pértigas dieléctricas",
    "Guantes dieléctricos (diferentes clases)",
    "Tapetes dieléctricos",
    "Kit de bloqueo y etiquetado (LOTO) completo",
    "Candados de seguridad y pinzas multiplicadoras",
    "Trípode de rescate para espacios confinados",
    "Winche o recuperador para trípode",
    "Arnés de seguridad de cuerpo entero (dieléctrico/ignífugo)",
    "Eslingas con absorbedor de impacto",
    "Líneas de vida retráctiles",
    "Polipastos de cadena (Tecle) de 1 a 5 ton",
    "Diferenciales de palanca (Señoritas) de 1.5 a 3 ton",
    "Tirfor (tecle de guaya pasante)",
    "Grilletes tipo lira (certificados)",
    "Cáncamos de elevación giratorios",
    "Eslingas de poliéster planas y tubulares",
    "Generador eléctrico portátil a gasolina/diésel",
    "Hidrolavadora industrial",
    "Aspiradora industrial para líquidos y sólidos",
    "Bombas sumergibles de achique",
    "Extensiones eléctricas de uso rudo",
    "Lámparas de trabajo LED recargables",
    "Bancos de trabajo móviles con tornillo de banco",
    "Cajas de herramientas tipo baúl metálico (Jobsite box)"
  ].map(h => ({ value: h, label: h }));

  const categorias = [
    { value: "electricas", label: "Eléctricas" },
    { value: "manuales", label: "Manuales" },
    { value: "medicion", label: "Medición" },
  ];
  const estados = [
    { value: "Nueva", label: "Nueva" },
    { value: "Dañada", label: "Dañada" },
    { value: "En mantenimiento", label: "En mantenimiento" },
  ];

  const fields = [
    { name: "nombre", label: "Nombre", type: "autocomplete", options: herramientasPredefinidas },
    { name: "codigo", label: "Código", type: "text" },
    { name: "categoria", label: "Categoría", type: "select", options: categorias },
    { name: "cantidad_disponible", label: "Cantidad", type: "number" },
    { name: "estado", label: "Estado", type: "select", options: estados },
  ];

  const handleSubmit = async (data) => {
    const token = localStorage.getItem("authToken");
    const decoded = jwtDecode(token);
    await handleCreateInventory({
      ...data,
      id_administrador: parseInt(decoded.id),
    });
  };

  return (
    <BaseFormModal
      title="Agregar herramienta"
      fields={fields}
      onSubmit={handleSubmit}
      onClose={onClose}
      onSuccess={onSuccess}
      successMessage="¡Herramienta registrada exitosamente!"
    />
  );
};

export default FormCreateInventoryAd;
