name: Build

on:
  push:
    branches:
      - development
      - jonier-development
  pull_request:
    branches:
      - development
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Para análisis más precisos (no shallow clone)

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: . # Donde está el sonar-project.properties (en la raíz del repo)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
