name: SonarCloud analysis


on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
  workflow_dispatch:


permissions:
  pull-requests: read


jobs:
  Analysis:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'


      - name: Install dependencies
        run: npm install
        working-directory: ./Backend




      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=FiveDevCode_A-C-Soluciones
            -Dsonar.organization=fivedevcode
            -Dsonar.javascript.lcov.reportPaths=./Backend/coverage/lcov.info
            -Dsonar.sources=./Backend/src
            -Dsonar.tests=./Backend/test
            -Dsonar.test.inclusions=**/*.test.js
            -Dsonar.verbose=true
            -Dsonar.exclusions=\
            **/controllers/cliente.controller.js,\
            **/models/cliente.model.js,\
            **/repository/cliente.repository.js,\
            **/services/cliente.services.js,\
            **/routers/cliente.routes.js,\
            **/hooks/encryptPassword.js,\
            **/database/conexion.js,\
            **/app.js,\
            **/index.js,\
            **/config/puerto.js

